
name: GitHub secrets
on: 
  workflow_dispatch:
jobs: 
 deployment:
 
  runs-on: ubuntu-latest
  steps: 
    - name: print secrets
      run: |
       echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}"
    - name: print secret as env variable
      run: |
       echo "MY_TOP_SECRET: $MY_TOP_SECRET"
       env:
        MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}