
name: Artifacts Demo
on: push
jobs:
 job_1:
  name: Upload Artifacts
  runs-on: self-hosted
  steps:
   - name: "create a local file"
     run: echo "I am storing data in this file , So i can use this in subsequent jobs" >> file.txt
   - uses: actions/Upload-artifact@v2
     with:
      name: file
      path: file.txt
      retention-days: 10
 job_2:
  name: Download artifact
  runs-on: self-hosted
  needs: job_1
  steps:
   - uses: actions/download-artifact@v2
