
name: GitHub Environments
on: 
 workflow_dispatch:
jobs:
  deployment:
   runs-on: [self-hosted, Linux, X64, Production]
   environment: 
     name: Production
     url: https://github.com
   steps: 
   - name: 'print secret from environment'
     run: | 
      echo "APP_SECRET: ${{ secrets.APP_SECRET }}"

