
name: List all default GitHub vars
on:
 workflow-dispatch:
jobs:
 ubuntu-environment-variables:
  runs-on: ubuntu-latest
  steps:
   - run: env
 macos-environment-variables:
  runs-on: macos-latest
  steps: 
   - run: env
