name: passing values to next jobs
on: workflow_dispatch
jobs:
 job1:
   runs-on: ubuntu-latest
   outputs: 
    output1: ${{steps.step1.outputs.test}}
    output2: ${{steps.step2.outputs.test}}
   steps:
    - id: step1 
      run: echo "::set-output name=test::Importvalue1"
    - id: step2 
      run: echo "::set-output name=test::Importvalue2"
 job2:
  runs-on: ubuntu-latest
  needs: job1
  steps:
  - run: |
      echo "printing the values"
      echo output1: ${{needs.job1.outputs.output1}}
      echo output2: ${{needs.job2.outputs.output2}}
  
 
